---
- hosts: win
# Don't gather hosts facts for performance
  gather_facts: no
  vars:
# Elasticsearch hosts
    elas_hosts: 192.168.56.103
    elas_hosts_port: 9200
# reinstall winlogbeat
    reinstall: true


# Setting the task
  tasks:
   - name: Preparing for Step Winlogbeat Stopped with ignore errors
     win_service:
       name: winlogbeat
       start_mode: auto
       state: stopped
     ignore_errors: true
     when: reinstall==true

   - name: Preparing for Step Remove directory
     win_file:
       path: C:\Program Files\winlogbeat
       state: absent
     ignore_errors: true
     when: reinstall==true

   - name: Preparing for Step Create work directory
     win_file:
       path: C:\work\
       state: directory

   - name: Preparing for Step Copy zip file of Winlogbeat
     win_copy:
       src: files/winlogbeat-1.2.3-windows.zip
       dest: C:\work\winlogbeat-1.2.3-windows.zip

   - name: Preparing for Step Decompression zip file
     win_unzip:
       src: C:\work\winlogbeat-1.2.3-windows.zip
       dest: C:\work\winlogbeat-1.2.3-windows\
       rm: true

   - name: Preparing for Step Move directory
     raw: Move-Item -Path "C:\work\winlogbeat-1.2.3-windows\" -Destination "C:\progra~1\winlogbeat\"

   - name: Preparing for Step Change config of Winlogbeat
     win_template:
       src: templates/winlogbeat.yml.j2
       dest: C:\progra~1\winlogbeat\winlogbeat.yml

   - name: Winlogbeat Step Installing Winlogbeat
     raw: PowerShell.exe -ExecutionPolicy UnRestricted -File C:\progra~1\winlogbeat\winlogbeat-1.2.3-windows\install-service-winlogbeat.ps1

   - name: Winlogbeat Step Starting Winlogbeat
     win_service:
       name: winlogbeat
       start_mode: auto
       state: started

